### ISSUE TITLE
Plexpy Script Dependency: plexapi

### ISSUE THREAD

**Issue by jrdnlc** [linuxserver/docker-tautulli#41]
Hey guys, can you guys integrate plexapi dependency into the docker? 

I’m using a few scripts on Plexpy that depend on it and currently install it manually by runing pip install plexapi. Would be great if you guys can add it so it can stop forgeting to re-add it every friday lol.

**Comment by aptalca** [comment]
We generally do not like to install custom scripts (or their dependencies).

You can create a bash script file on your host that contains the `pip install plexapi` and map that file in your docker run command as `-v /path/to/script:/etc/cont-init.d/40-plexapi`

It will run that script/command every time the container is restarted before the plexpy service is launched

**Comment by jrdnlc** [comment]
Any reason why other dependancies are included already in the docker then? Still don’t inderstand why it cant cant be included it when other custom script dependencies are already there. 

I mean custom scripts is part of a Plexpy feature so why prevent users from using that by not including dependencies that are needed?

**Comment by aptalca** [comment]
?? I don't believe there are any. All that's included is what is required by plexpy's internal functions. It's really just python and pycryptodomex, that's all.

**Comment by jrdnlc** [comment]
There are a few that customs scripts use. But if it’s part of a plexpy to be able to use custom scripts why not add what the users need to be able to fully use that feature? 

I’m not asking if you guys use custom scripts. I’m talking about myself and other users in general. The users perspective. You guys will only add it if your team needs it? Seems like how it is which just makes you guys look bad. 

Im not asking for something that will break your docker neither asking you to add features to it. Just asking for something that will allow me to use a feature that plexpy has built-in.

**Comment by aptalca** [comment]
You're asking us to add an unofficial 3rd party api framework for plex. It would be an added feature, and it is not a built-in feature of plexpy. That is beyond the scope of this docker image. We don't want to have to support that external framework, nor do we want to jeopardize that framework potentially breaking our image during a weekly refresh. We have a lot of docker images to support, a handful of volunteer devs who are busy with full time jobs and personal lives, so we like to keep our images simple.

You're the only who requested that and it's likely a fringe use case. If more people start asking for it, we'll reconsider.

I already provided you with a simple solution that will work for you.

**Comment by CHBMB** [comment]
If you feel that strongly, fork it and build your own, I can assure you we don't add stuff just because we want it, I personally modify containers on my machine and don't request anything be pushed back upstream and I know that the rest of ls.io also do the same.  

If you can find an example of the practice you're alluding to then please point it out.  We've had this conversation with a number of people who want THE essential dependency for their personal use case on other containers and always give the same answer which is what @aptalca has given you, with a very easy to implement way to achieve what you want, without requiring us to change the docker container based on a single person asking.

Every dependency we add to a container increases the complexity and chance of breakage.  If we integrate the plexapi, suddenly it becomes our problem if it breaks.  The solution aptalca has suggested reduces our workload and means that a problem with the plexapi doesn't mean the container is broken for the vast majority of people who aren't using it.

**Comment by Hellowlol** [comment]
Thanks for a way to work around this.

**Comment by sparklyballs** [comment]
LTNS @Hellowlol

**Comment by Hellowlol** [comment]
Yeah, same to you. Im in the progress of converting the stuff running on my desktop to your dockers and I didnt understand why my nzbtomedia script didnt work. I guess this is the workaround that i have to use.

**Comment by sparklyballs** [comment]
@Hellowlol i run a nzbtomedia script between sab and medusa to supposedly handle failed downloads 

one silly little thing that's easy to overlook is making the script executable by sab (or insert other downloader here)

**Comment by Hellowlol** [comment]
Funny you should say that. I forgot that and forgot to disable nzbmedia transcoding. It work as a charm after that.
